### ISSUE TITLE
Possible bug under annotated_matrix2d.hpp while initializing gloabl/local_colgrps using init_colgrps()

### ISSUE THREAD

**Issue by hmofrad** [cmuq-ccl/LA3#1]
The `init_colgrps(local_colgrp_indices)` method is using `tile_height` to calculate the `colgrp.endpos` of local group in `colgrp.endpos = colgrp.offset + tile_height;`. IMO, this should be `colgrp.endpos = colgrp.offset + tile_width;`, given we're initializing column wise. I guess this hasn't showed its effect as `tile_height == tile_width` and we're dealing with square matrices.

**Comment by okhat** [comment]
You're right, the intention is `tile_width`. The code is peppered with assertions like `tile_width == tile_height`, `nrows == ncols`, etc., so this sort of thing should have no effect though.

**Comment by hmofrad** [comment]
Ah! Thanks for clearing this.
