### ISSUE TITLE
Possible opimization.

### ISSUE THREAD

**Issue by hmofrad** [cmuq-ccl/LA3#2]
The `Env::shuffle_rank` can be optimized a little by initializing `ranks` by zero and passing the 2nd index of `ranks` vector to `iota` alongside giving the starting value of 1.

`std::iota(ranks.begin() + 1, ranks.end(), 1);`

Then, `random_shuffle` can be changed as follows:
`std::random_shuffle(ranks.begin() + 1, ranks.end());`

Basically the `Env::shuffle_ranks` code block can be rewritten as follows:

void Env::shuffle_ranks(RankOrder order)
{
std::vector<int> ranks(nranks, 0); // Initialize by 0
  if (is_master)
  {
    int seed = order == RankOrder::FIXED_SHUFFLE ? 0 : now();
    srand(seed);
    std::iota(ranks.begin() + 1, ranks.end(), 1);  // ranks = range(len(ranks))
    std::random_shuffle(ranks.begin() + 1, ranks.end());
  }
// Rest are the same

**Comment by okhat** [comment]
Sounds good, thanks for suggesting.
I assume we can replace `ranks.begin()` with `ranks.begin() + 1` in `std::random_shuffle(ranks.begin(), ranks.end());` in the current code and remove the `swap`, keeping all else. Is that right?
Feel free to push both your suggestions directly.

**Comment by hmofrad** [comment]
Yes, your right! the `iota` changes are not necessary! I'll commit the `random_shuffle` part then.
Thanks.

**Comment by hmofrad** [comment]
Out of curiosity! What's the rationale behind shuffling ranks?

**Comment by okhat** [comment]
Consider running 16 processes on 4 nodes. Depending on the flags (e.g., `-ppn`), the processes on the same node will either be given consecutive ranks or be separated by steps of +4. In both cases, we will have 4 ranks per row-group and 4 ranks per column-group. The placement will thus end up being 1D by row or 1D by col (depending on `-ppn`) across nodes, even though it's 2D cyclic/staggered across processes.

**Comment by hmofrad** [comment]
Interesting! I assume, if we have this underlying assumption then shuffling of ranks would help having a better load balancing while using 2D. 
Thanks.
So, I'm going to close this issue as I committed the changes in master.
