### ISSUE TITLE
Type casting without loss of precision 

### ISSUE THREAD

**Issue by hmofrad** [cmuq-ccl/LA3#4]
There's a line in main method of apps e.g. `pr app` which reads in the number of vertices using `atol`: `vid_t nvertices = (vid_t) std::atol(argv[2]);`. Given, the `vid_t` is an type alias of `uint32_t` and `atol` return `long int`, there's a possible loss of precision for graphs with more than 4 B vertices.

If we assume no body is going to use the platform for graphs with more than 4B vertices, I suggest using `atoi` which return `int` which has size equal to `uint32_t` on all architectures.
If we need to support graphs with more than 4B vertices, we have to run a refactor all over the code and change `nvertices`, `mvertices`, `nrows`, `ncols` and etc. from `unit32_t` to `uint64_t`.

**Comment by okhat** [comment]
A refactor to allow switching between 32- and 64-bit vertex indices (e.g., as a template parameter) would be nice in the long term. As for `std::atol`, I don't think that's an issue, especially it's in application code, so let it cover a generic/wide range. Note `std::atoi` would return a signed int anyway before the cast.

**Comment by hmofrad** [comment]
I was thinking to just support for 64-bit vertices but yes this would be even better.  About `atoi`, again yes and without this casting the supported #vertices could be reduced to 2B.  So, I guess it's good to add this feature in the future as for now I assume the range is enough to support a wide range of graphs.

**Comment by okhat** [comment]
Only supporting 64-bit vertices doubles the sizes of the graphs on disk and their representations in memory, hence the long-term suggestion above.
